<a href="https://colab.research.google.com/github/KKugi/Big-Data/blob/main/map.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Map

In [ ]:
import pandas as pd

In [ ]:
hollys = pd.read_csv('hollys.csv',encoding='CP949',index_col=0, header=0,engine='python')
hollys.head()

      store                                  address          phone
0  부산서면일번가점                       부산광역시 신천대로 62번길 74   051-802-2550
1   전주혁신도시점                           전주시 완산구 오공로 33   063-221-3361
2    이인휴게소점                      충남 공주시 이인면 이인리 3-8   010-5406-5747
3    도심공항2점  서울시 강남구 테헤란로 87길 22 (도심공항터미널 2층 203-1호)   02-2016-5400
4     경복궁역점                     서울특별시 종로구 자하문로  14-1    02-720-5589

In [ ]:
addr = []
for address in hollys.address:
    addr.append(str(address).split())
addr

[['부산광역시', '신천대로', '62번길', '74'],
 ['전주시', '완산구', '오공로', '33'],
 ['충남', '공주시', '이인면', '이인리', '3-8'],
 ['서울시', '강남구', '테헤란로', '87길', '22', '(도심공항터미널', '2층', '203-1호)'],
 ['서울특별시', '종로구', '자하문로', '14-1'],
 ['충청남도', '당진군', '신평면', '서해안고속도로', '275'],
 ['경기도', '안양시', '동안구', '동편로', '6'],
 ['서울특별시', '서초구', '신반포로', '15', '구반포상가', 'G동', '1층'],
 ['대구광역시', '달서구', '상화북로', '194,', '2층'],
 ['경기도', '수원시', '팔달구', '효원로', '299'],
 ['경기도', '수원시', '영통구', '청명남로', '10'],
 ['경기도', '수원시', '팔달구', '향교로', '6(매산로1가,1-3층)'],
 ['서울시', '종로구', '종로5길', '68'],
 ['경기', '파주시', '중앙로', '328', '엠에이치타워', '1층'],
 ['경북', '구미시', '구미중앙로', '44,', '마이구미CGV', '복합건물', '1층'],
 ['인천광역시', '서구', '중봉대로', '612번길', '16', '서후센타시아', '1층'],
 ['경기도', '김포시', '황금로', '109번길', '27'],
 ['충청북도', '진천군', '진천읍', '중앙북로', '28,', '2층'],
 ['경기', '평택시', '평택1로', '11'],
 ['경북', '칠곡군', '왜관읍', '경부고속도로', '159'],
 ['대구광역시', '북구', '구암로', '59', '비전스케어', '1~2층'],
 ['서울특별시', '강남구', '학동로', '219,', '2층'],
 ['충청북도', '청주시', '서원구', '신성화로', '39'],
 ['부산시', '강서구', '대저2동', '2350', '국제선', '청사', '3층'],
 ['서울특별시', '마포구', '양화로', '36'],
 ['서울특별시', '중구', '장충단로', '251', '2,3층'],
 ['서울시', '강동구', '상일로', '151'],
 ['광주광역시', '북구', '첨단연신로91번길', '10'],
 ['광주광역시', '광산구', '용아로', '400'],
 ['전북', '익산시', '선화로3길', '16-10'],
 ['전라남도', '영광군', '영광읍', '중앙로', '180-2'],
 ['서울시', '관악구', '신림로', '313'],
 ['서울특별시', '영등포구', '도림로', '140'],
 ['부산광역시', '해운대구', '달맞이길', '199,', '2~3층'],
 ['광주광역시', '북구', '비엔날레로', '109-1'],
 ['경기도', '성남시', '수정구', '산성대로', '265', '2층'],
 ['경상북도', '경주시', '보불로', '305'],
 ['강원도', '원주시', '중평길', '4'],
 ['경기도', '성남시', '분당구', '판교역로241번길', '22'],
 ['부산시', '해운대구', '송정광어골로', '77'],
 ['경상북도', '구미시', '인동가산로', '20,', '1~2층'],
 ['전북', '전주시', '덕진구', '붓내3길', '17'],
 ['서울특별시', '강남구', '도곡로', '414'],
 ['서울시', '강남구', '테헤란로', '406'],
 ['경기도', '양주시', '평화로', '1593'],
 ['서울시', '중구', '퇴계로20길', '2'],
 ['부산광역시', '부산진구', '동천로', '73,', 'DS타워', '1~2층'],
 ['광주광역시', '서구', '상무시민로', '130'],
 ['서울특별시', '마포구', '홍익로', '4'],
 ['서울특별시', '용산구', '이태원로', '179'],
 ['충청북도', '청주시', '서원구', '월평로', '4', '1,', '2층'],
 ['충청북도', '청주시', '흥덕구', '가경동', '1746'],
 ['인천시', '남동구', '석산로', '11'],
 ['광주광역시', '광산구', '풍영로', '189'],
 ['경상북도', '경주시', '황성로28번길', '15', '1~2층'],
 ['경기', '양주시', '광적면', '부흥로', '847'],
 ['경기', '동두천시', '중앙로', '110-13', '게림프라자', '1층'],
 ['인천', '남동구', '소래역남로', '22', '에코프라자', '114호,', '206호'],
 ['서울시', '중구', '중림로', '21'],
 ['강원도', '강릉시', '창해로14번길', '51-20'],
 ['전라북도', '전주시', '완산구', '우전로', '255'],
 ['경기도', '시흥시', '중심상가', '4길', '10,', '1층'],
 ['충청남도', '천안시', '서북구', '오성6길', '52,', '1층'],
 ['서울특별시', '서대문구', '응암로', '89'],
 ['경기도', '의왕시', '오전로', '18'],
 ['전라북도', '전주시', '덕진구', '아중로', '193'],
 ['경기도', '안산시', '단원구', '선부광장1로', '56'],
 ['경기도', '안산시', '상록구', '중보로', '31'],
 ['경기도', '화성시', '봉담읍', '와우안길', '22'],
 ['인천광역시', '부평구', '길주로', '623'],
 ['광주광역시', '서구', '풍금로38번길', '11'],
 ['강원도', '원주시', '장미공원길', '27-9'],
 ['경기도', '오산시', '원동로7번길', '35'],
 ['경기도', '수원시', '장안구', '서부로2126번길', '10,', '1층'],
 ['부산광역시', '영도구', '태종로', '98,', '모닝아일랜드', '상가', '2층'],
 ['전라북도', '전주시', '완산구', '효자로', '289,', '신화빌딩', '1층yl'],
 ['서울', '동작구', '노량진로', '157'],
 ['경기도', '안산시', '단원구', '중앙대로', '907'],
 ['인천광역시', '계양구', '도두리로', '14'],
 ['경기도', '광명시', '철산로', '20'],
 ['서울시', '서대문구', '통일로', '451'],
 ['부산광역시', '중구', '광복로', '73-2'],
 ['경상북도', '영천시', '청통면', '청통로', '334-42'],
 ['경상북도', '경산시', '와촌면', '강학길', '103'],
 ['충청북도', '청주시', '흥덕구', '백봉로223번길', '7'],
 ['서울시', '관악구', '신림로', '353-1'],
 ['서서울', '관악구', '관악로', '172,', '2층'],
 ['서울시', '서초구', '신반포로', '194', '고속버스터미널', '9호선', '연결', '통로', '12,13,14호'],
 ['전라남도', '목포시', '옥암로', '95'],
 ['경기도', '수원시', '영통구', '덕영대로', '1693'],
 ['서울시', '강남구', '도곡로', '213'],
 ['충청북도', '청주시', '흥덕구', '2순환로1167번길', '5,', '1~2층'],
 ['충청북도', '청주시', '흥덕구', '내수동로', '53,', '1~2층'],
 ['광주', '서구', '하남대로680번길', '1'],
 ['충청남도', '금산군', '군북면', '대암길', '34-30'],
 ['경상북도', '군위군', '군위읍', '오곡리', '67-5'],
 ['울산시', '남구', '삼산중로', '50,', '2층'],
 ['경상북도', '군위군', '군위읍', '오곡리', '산', '68-8l'],
 ['대구광역시', '달성군', '현풍면', '성하리', '286'],
 ['대구광역시', '달성군', '현풍면', '성하리', '342']]

In [ ]:
addr[0][0]

'부산광역시'

In [ ]:
addr2 = []
for i in range(len(addr)):
    if addr[i][0] == "서울": addr[i][0] = "서울특별시"
    elif addr[i][0] == "서울시": addr[i][0] = "서울특별시"
    elif addr[i][0] == "서서울": addr[i][0] = "서울특별시"
    elif addr[i][0] == "부산시": addr[i][0] = "부산광역시"
    elif addr[i][0] == "인천": addr[i][0] = "인천광역시"
    elif addr[i][0] == "인천시": addr[i][0] = "인천광역시"
    elif addr[i][0] == "광주": addr[i][0] = "광주광역시"
    elif addr[i][0] == "대전시": addr[i][0] = "대전광역시"
    elif addr[i][0] == "울산시": addr[i][0] = "울산광역시"
    elif addr[i][0] == "세종시": addr[i][0] = "세종특별자치시"
    elif addr[i][0] == "경기": addr[i][0] = "경기도"
    elif addr[i][0] == "충북": addr[i][0] = "충청북도"
    elif addr[i][0] == "충남": addr[i][0] = "충청남도"
    elif addr[i][0] == "전주시": addr[i][0] = "전라북도 전주시"
    elif addr[i][0] == "전북": addr[i][0] = "전라북도"
    elif addr[i][0] == "전남": addr[i][0] = "전라남도"
    elif addr[i][0] == "경북": addr[i][0] = "경상북도"
    elif addr[i][0] == "경남": addr[i][0] = "경상남도"
    elif addr[i][0] == "제주": addr[i][0] = "제주특별자치도"
    elif addr[i][0] == "제주도": addr[i][0] = "제주특별자치도"
    elif addr[i][0] == "제주시": addr[i][0] = "제주특별자치도"
    addr2.append(' '.join(addr[i]))
addr2

['부산광역시 신천대로 62번길 74',
 '전라북도 전주시 완산구 오공로 33',
 '충청남도 공주시 이인면 이인리 3-8',
 '서울특별시 강남구 테헤란로 87길 22 (도심공항터미널 2층 203-1호)',
 '서울특별시 종로구 자하문로 14-1',
 '충청남도 당진군 신평면 서해안고속도로 275',
 '경기도 안양시 동안구 동편로 6',
 '서울특별시 서초구 신반포로 15 구반포상가 G동 1층',
 '대구광역시 달서구 상화북로 194, 2층',
 '경기도 수원시 팔달구 효원로 299',
 '경기도 수원시 영통구 청명남로 10',
 '경기도 수원시 팔달구 향교로 6(매산로1가,1-3층)',
 '서울특별시 종로구 종로5길 68',
 '경기도 파주시 중앙로 328 엠에이치타워 1층',
 '경상북도 구미시 구미중앙로 44, 마이구미CGV 복합건물 1층',
 '인천광역시 서구 중봉대로 612번길 16 서후센타시아 1층',
 '경기도 김포시 황금로 109번길 27',
 '충청북도 진천군 진천읍 중앙북로 28, 2층',
 '경기도 평택시 평택1로 11',
 '경상북도 칠곡군 왜관읍 경부고속도로 159',
 '대구광역시 북구 구암로 59 비전스케어 1~2층',
 '서울특별시 강남구 학동로 219, 2층',
 '충청북도 청주시 서원구 신성화로 39',
 '부산광역시 강서구 대저2동 2350 국제선 청사 3층',
 '서울특별시 마포구 양화로 36',
 '서울특별시 중구 장충단로 251 2,3층',
 '서울특별시 강동구 상일로 151',
 '광주광역시 북구 첨단연신로91번길 10',
 '광주광역시 광산구 용아로 400',
 '전라북도 익산시 선화로3길 16-10',
 '전라남도 영광군 영광읍 중앙로 180-2',
 '서울특별시 관악구 신림로 313',
 '서울특별시 영등포구 도림로 140',
 '부산광역시 해운대구 달맞이길 199, 2~3층',
 '광주광역시 북구 비엔날레로 109-1',
 '경기도 성남시 수정구 산성대로 265 2층',
 '경상북도 경주시 보불로 305',
 '강원도 원주시 중평길 4',
 '경기도 성남시 분당구 판교역로241번길 22',
 '부산광역시 해운대구 송정광어골로 77',
 '경상북도 구미시 인동가산로 20, 1~2층',
 '전라북도 전주시 덕진구 붓내3길 17',
 '서울특별시 강남구 도곡로 414',
 '서울특별시 강남구 테헤란로 406',
 '경기도 양주시 평화로 1593',
 '서울특별시 중구 퇴계로20길 2',
 '부산광역시 부산진구 동천로 73, DS타워 1~2층',
 '광주광역시 서구 상무시민로 130',
 '서울특별시 마포구 홍익로 4',
 '서울특별시 용산구 이태원로 179',
 '충청북도 청주시 서원구 월평로 4 1, 2층',
 '충청북도 청주시 흥덕구 가경동 1746',
 '인천광역시 남동구 석산로 11',
 '광주광역시 광산구 풍영로 189',
 '경상북도 경주시 황성로28번길 15 1~2층',
 '경기도 양주시 광적면 부흥로 847',
 '경기도 동두천시 중앙로 110-13 게림프라자 1층',
 '인천광역시 남동구 소래역남로 22 에코프라자 114호, 206호',
 '서울특별시 중구 중림로 21',
 '강원도 강릉시 창해로14번길 51-20',
 '전라북도 전주시 완산구 우전로 255',
 '경기도 시흥시 중심상가 4길 10, 1층',
 '충청남도 천안시 서북구 오성6길 52, 1층',
 '서울특별시 서대문구 응암로 89',
 '경기도 의왕시 오전로 18',
 '전라북도 전주시 덕진구 아중로 193',
 '경기도 안산시 단원구 선부광장1로 56',
 '경기도 안산시 상록구 중보로 31',
 '경기도 화성시 봉담읍 와우안길 22',
 '인천광역시 부평구 길주로 623',
 '광주광역시 서구 풍금로38번길 11',
 '강원도 원주시 장미공원길 27-9',
 '경기도 오산시 원동로7번길 35',
 '경기도 수원시 장안구 서부로2126번길 10, 1층',
 '부산광역시 영도구 태종로 98, 모닝아일랜드 상가 2층',
 '전라북도 전주시 완산구 효자로 289, 신화빌딩 1층yl',
 '서울특별시 동작구 노량진로 157',
 '경기도 안산시 단원구 중앙대로 907',
 '인천광역시 계양구 도두리로 14',
 '경기도 광명시 철산로 20',
 '서울특별시 서대문구 통일로 451',
 '부산광역시 중구 광복로 73-2',
 '경상북도 영천시 청통면 청통로 334-42',
 '경상북도 경산시 와촌면 강학길 103',
 '충청북도 청주시 흥덕구 백봉로223번길 7',
 '서울특별시 관악구 신림로 353-1',
 '서울특별시 관악구 관악로 172, 2층',
 '서울특별시 서초구 신반포로 194 고속버스터미널 9호선 연결 통로 12,13,14호',
 '전라남도 목포시 옥암로 95',
 '경기도 수원시 영통구 덕영대로 1693',
 '서울특별시 강남구 도곡로 213',
 '충청북도 청주시 흥덕구 2순환로1167번길 5, 1~2층',
 '충청북도 청주시 흥덕구 내수동로 53, 1~2층',
 '광주광역시 서구 하남대로680번길 1',
 '충청남도 금산군 군북면 대암길 34-30',
 '경상북도 군위군 군위읍 오곡리 67-5',
 '울산광역시 남구 삼산중로 50, 2층',
 '경상북도 군위군 군위읍 오곡리 산 68-8l',
 '대구광역시 달성군 현풍면 성하리 286',
 '대구광역시 달성군 현풍면 성하리 342']

In [ ]:
addr2 = pd.DataFrame(addr2,columns=['address2'])
addr2

                                     address2
0                          부산광역시 신천대로 62번길 74
1                         전라북도 전주시 완산구 오공로 33
2                        충청남도 공주시 이인면 이인리 3-8
3   서울특별시 강남구 테헤란로 87길 22 (도심공항터미널 2층 203-1호)
4                         서울특별시 종로구 자하문로 14-1
..                                        ...
95                      경상북도 군위군 군위읍 오곡리 67-5
96                       울산광역시 남구 삼산중로 50, 2층
97                   경상북도 군위군 군위읍 오곡리 산 68-8l
98                      대구광역시 달성군 현풍면 성하리 286
99                      대구광역시 달성군 현풍면 성하리 342

[100 rows x 1 columns]

In [ ]:
hollys.head()

      store                                  address          phone
0  부산서면일번가점                       부산광역시 신천대로 62번길 74   051-802-2550
1   전주혁신도시점                           전주시 완산구 오공로 33   063-221-3361
2    이인휴게소점                      충남 공주시 이인면 이인리 3-8   010-5406-5747
3    도심공항2점  서울시 강남구 테헤란로 87길 22 (도심공항터미널 2층 203-1호)   02-2016-5400
4     경복궁역점                     서울특별시 종로구 자하문로  14-1    02-720-5589

In [ ]:
hollys2 = pd.concat([hollys,addr2],axis=1)
hollys2

        store  ...                                   address2
0    부산서면일번가점  ...                         부산광역시 신천대로 62번길 74
1     전주혁신도시점  ...                        전라북도 전주시 완산구 오공로 33
2      이인휴게소점  ...                       충청남도 공주시 이인면 이인리 3-8
3      도심공항2점  ...  서울특별시 강남구 테헤란로 87길 22 (도심공항터미널 2층 203-1호)
4       경복궁역점  ...                        서울특별시 종로구 자하문로 14-1
..        ...  ...                                        ...
95  군위휴게소(하)점  ...                      경상북도 군위군 군위읍 오곡리 67-5
96      울산삼산점  ...                       울산광역시 남구 삼산중로 50, 2층
97  군위휴게소(상)점  ...                   경상북도 군위군 군위읍 오곡리 산 68-8l
98  현풍휴게소(하)점  ...                      대구광역시 달성군 현풍면 성하리 286
99  현풍휴게소(상)점  ...                      대구광역시 달성군 현풍면 성하리 342

[100 rows x 4 columns]

In [ ]:
import folium

In [ ]:
map_ho = folium.Map(location=[36.54100095967711, 128.79629698726797],zoom_start=16)
map_ho.save('map_ho.html')

In [ ]:
Hy_geoData = pd.read_csv('hollysgeo.shp.csv',encoding='cp949', engine='python')
Hy_geoData

     No  Unnamed: 1      store  ...          경도         위도    상태
0     1           0   부산서면일번가점  ...  129.058514  35.154061   정좌표
1     2           1    전주혁신도시점  ...  127.058992  35.836210   정좌표
2     3           2     이인휴게소점  ...  127.068053  36.353047   정좌표
3     4           3     도심공항2점  ...  127.059443  37.509632   정좌표
4     5           4      경복궁역점  ...  126.972420  37.577483   정좌표
..  ...         ...        ...  ...         ...        ...   ...
95   96          95  군위휴게소(하)점  ...  128.590015  36.273981  인근좌표
96   97          96      울산삼산점  ...  129.335921  35.538006   정좌표
97   98          97  군위휴게소(상)점  ...  128.577414  36.267175  인근좌표
98   99          98  현풍휴게소(하)점  ...  128.433256  35.702078  인근좌표
99  100          99  현풍휴게소(상)점  ...  128.436658  35.702270   정좌표

[100 rows x 8 columns]

In [ ]:
Hy_geoData.head()

   No  Unnamed: 1     store  ...          경도         위도   상태
0   1           0  부산서면일번가점  ...  129.058514  35.154061  정좌표
1   2           1   전주혁신도시점  ...  127.058992  35.836210  정좌표
2   3           2    이인휴게소점  ...  127.068053  36.353047  정좌표
3   4           3    도심공항2점  ...  127.059443  37.509632  정좌표
4   5           4     경복궁역점  ...  126.972420  37.577483  정좌표

[5 rows x 8 columns]

In [ ]:
map_Hy = folium.Map(location = [36.54100095967711, 128.79629698726797], zoom_start = 15)
map_Hy

In [ ]:
for i, store in Hy_geoData.iterrows(): 
    folium.Marker(location=[store['위도'],store['경도']],popup=store['store'],
                  icon = folium.Icon(color='red',icon='star')).add_to(map_Hy)

In [ ]:
map_Hy.save('map_Hy.html')